# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 Dell Inc, or its subsidiaries.
---
- name: OS deployment using Virtual Media
  # From: https://developer.dell.com/apis/9008/versions/1.0/docs/Tutorials/iDRAC%20Modules/Deploy-operating-systems-on-PowerEdge-servers-using-Virtual-Media.md
  hosts: dh1bmc
  become: true
  gather_facts: False
  vars:
    retries_count: 60
    interval: 60

  collections:
    - dellemc.openmanage

  tasks:

  - name: Set iDRAC virtual media attach attribute to attached.
    idrac_attributes:
      idrac_ip: "{{ inventory_hostname }}"
      idrac_user: "{{ user }}"
      idrac_password: "{{ password }}"
      validate_certs: False
      idrac_attributes:
        VirtualMedia.1.Attached: "Attached"
