name: Ansible

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Ansible lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install necessary collections for validation
      - name: Install Ansible Galaxy Collections
        run: |
          ansible-galaxy collection install arista.eos community.general f5networks.f5_modules community.docker

      # Set Ansible Collection Path dynamically
      - name: Set Ansible Collection Path
        run: |
          echo "ANSIBLE_COLLECTION_PATHS=$(ansible-galaxy collection list | grep -Eo '/.*')" >> $GITHUB_ENV

      # Run ansible-lint with the set collection path
      - uses: ansible/ansible-lint@v24.9.2
        with:
          working_directory: ./ansible
        env:
          ANSIBLE_COLLECTION_PATHS: ${{ env.ANSIBLE_COLLECTION_PATHS }}
