name: Ansible

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Ansible lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install required Ansible collections
      - name: Install Ansible collections
        run: |
          ansible-galaxy collection install arista.eos
          ansible-galaxy collection install community.general
          ansible-galaxy collection install f5networks.f5_modules
          ansible-galaxy collection install community.docker

      # Run ansible-lint
      - uses: ansible/ansible-lint@v24.9.2
        with:
          working_directory: ./ansible
