name: Ansible

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Ansible lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ansible/ansible-lint@v24.9.2
        with:
          working_directory: ./ansible
          requirements_file: ./collections/requirements.yml

# TODO: add build, test, ut, docs, ...
