name: Ansible

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Ansible lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install Ansible
      - name: Install Ansible
        run: |
          python3 -m pip install ansible ansible-lint

      # Install required Ansible collections
      - name: Install Ansible collections
        run: |
          ansible-galaxy collection install arista.eos
          ansible-galaxy collection install community.general
          ansible-galaxy collection install f5networks.f5_modules
          ansible-galaxy collection install community.docker

      # Set Ansible Collection Path
      - name: Set Ansible Collection Path
        run: |
          echo "ANSIBLE_COLLECTIONS_PATHS=$(ansible-galaxy collection list | grep -Eo '/.*')" >> $GITHUB_ENV

      # Run ansible-lint with FQCN resolution
      - name: Run ansible-lint
        env:
          ANSIBLE_COLLECTIONS_PATHS: ${{ env.ANSIBLE_COLLECTIONS_PATHS }}
        run: ansible-lint ./ansible
